import tkinter as tk
from tkinter import filedialog

from PIL import Image, ImageTk
import numpy as np
import tensorflow as tf  # Hoặc thư viện deep learning mà bạn đã sử dụng


# Load mô hình đã được đào tạo
from keras.src.optimizers import Adamax
from tensorflow.python.keras.models import load_model

loaded_model = tf.keras.models.load_model('model.h5', compile=False)
loaded_model.compile(Adamax(learning_rate= 0.001), loss= 'categorical_crossentropy', metrics= ['accuracy'])

# Global variable to store the selected image path
selected_image_path = None

def classify_image():
    global selected_image_path
    if selected_image_path:
        # Code để đọc hình ảnh và chuyển đổi nó thành đầu vào có thể được sử dụng bởi mô hình
        # Đây chỉ là một ví dụ đơn giản
        image = load_and_preprocess_image(selected_image_path)
        # Make predictions
        predictions = loaded_model.predict(image)

        # Giả định prediction là kết quả từ mô hình, ví dụ: [0.2, 0.5, 0.3] (xác suất của các lớp)
        # Bạn cần thay thế phần này bằng mã thực hiện việc dự đoán từ mô hình của bạn
        # Giả định prediction là mảng xác suất của các lớp, ví dụ: [0.2, 0.5, 0.3] (đã được thay thế bằng kết quả từ mô hình)
        class_names = ['DALMATIAN PELICAN', 'BLACK BREASTED PUFFBIRD', 'WATTLED CURASSOW', 'AMERICAN WIGEON', 'CARMINE BEE-EATER',
                 'GAMBELS QUAIL', 'UMBRELLA BIRD', 'AMERICAN KESTREL', 'AMERICAN GOLDFINCH', 'BLUE GROSBEAK',
                 'PALM NUT VULTURE', 'DUSKY LORY', 'AUCKLAND SHAQ', 'BLACK THROATED WARBLER', 'YELLOW CACIQUE',
                 'STRIPPED SWALLOW', 'VERMILION FLYCATHER', 'CAPE MAY WARBLER', 'RED TAILED HAWK', 'GURNEYS PITTA',
                 'INDIAN ROLLER', 'SNOW GOOSE', 'GREEN WINGED DOVE', 'AZURE TANAGER', 'GREEN MAGPIE', 'BANDED BROADBILL',
                 'AFRICAN PYGMY GOOSE', 'INDIGO FLYCATCHER', 'GREY PLOVER', 'TOUCHAN', 'HYACINTH MACAW', 'HARLEQUIN DUCK',
                 'ABYSSINIAN GROUND HORNBILL', 'CALIFORNIA QUAIL', 'BALD IBIS', 'WOOD THRUSH', 'RUBY THROATED HUMMINGBIRD',
                 'INDIGO BUNTING', 'ALBERTS TOWHEE', 'SORA', 'HOODED MERGANSER', 'ROSEATE SPOONBILL', 'CAPE ROCK THRUSH',
                 'BLUE COAU', 'CALIFORNIA CONDOR', 'BORNEAN PHEASANT', 'BARN SWALLOW', 'TAIWAN MAGPIE', 'SPLENDID WREN',
                 'RED BILLED TROPICBIRD', 'BLACK THROATED BUSHTIT', 'CHINESE POND HERON', 'AFRICAN EMERALD CUCKOO',
                 'COMMON LOON', 'COMMON POORWILL', 'ROSE BREASTED COCKATOO', 'FIORDLAND PENGUIN', 'SUPERB STARLING',
                 'CUBAN TODY', 'TASMANIAN HEN', 'BLACK SWAN', 'WATTLED LAPWING', 'RED NAPED TROGON', 'SUNBITTERN',
                 'AMERICAN PIPIT', 'OILBIRD', 'EASTERN TOWEE', 'GYRFALCON', 'BLACK SKIMMER', 'RED BEARDED BEE EATER',
                 'ASIAN OPENBILL STORK', 'ALBATROSS', 'WHITE EARED HUMMINGBIRD', 'EGYPTIAN GOOSE', 'MASKED LAPWING',
                 'LAUGHING GULL', 'AMERICAN ROBIN', 'MALABAR HORNBILL', 'OCELLATED TURKEY', 'PEREGRINE FALCON',
                 'SQUACCO HERON', 'CHINESE BAMBOO PARTRIDGE', 'IBISBILL', 'ROSY FACED LOVEBIRD', 'GREATOR SAGE GROUSE',
                 'MILITARY MACAW', 'CHATTERING LORY', 'VISAYAN HORNBILL', 'AZARAS SPINETAIL', 'RUFOUS KINGFISHER',
                 'LOONEY BIRDS', 'JABIRU', 'WHITE BREASTED WATERHEN', 'GREAT KISKADEE', 'GRAY KINGBIRD', 'GUINEAFOWL',
                 'NORTHERN MOCKINGBIRD', 'WHITE CRESTED HORNBILL', 'MALLARD DUCK', 'GILA WOODPECKER',
                 'BROWN HEADED COWBIRD', 'MASKED BOOBY', 'AMERICAN BITTERN', 'CALIFORNIA GULL', 'CASPIAN TERN',
                 'EMERALD TANAGER', 'BANDED PITA', 'AZURE JAY', 'BARRED PUFFBIRD', 'ELEGANT TROGON', 'SNOWY EGRET',
                 'EUROPEAN TURTLE DOVE', 'CRESTED SHRIKETIT', 'SATYR TRAGOPAN', 'GANG GANG COCKATOO', 'AMETHYST WOODSTAR',
                 'RED HEADED WOODPECKER', 'MIKADO  PHEASANT', 'FIRE TAILLED MYZORNIS', 'BUFFLEHEAD',
                 'BLUE THROATED PIPING GUAN', 'GREAT TINAMOU', 'SWINHOES PHEASANT', 'PARADISE TANAGER', 'OVENBIRD',
                 'GRANDALA', 'EASTERN BLUEBONNET', 'MOURNING DOVE', 'BLACK FACED SPOONBILL', 'BROWN NOODY', 'WALL CREAPER',
                 'ORIENTAL BAY OWL', 'DOWNY WOODPECKER', 'EMPEROR PENGUIN', 'WHITE TAILED TROPIC', 'FIERY MINIVET',
                 'OSPREY', 'HOUSE FINCH', 'SNOWY PLOVER', 'AMERICAN COOT', 'GOLDEN PIPIT', 'PUFFIN', 'ARARIPE MANAKIN',
                 'RUDY KINGFISHER', 'CABOTS TRAGOPAN', 'BLACK-CAPPED CHICKADEE', 'ABBOTTS BABBLER', 'GREEN BROADBILL',
                 'KAKAPO', 'RAZORBILL', 'RED LEGGED HONEYCREEPER', 'BLACK BAZA', 'ANTILLEAN EUPHONIA', 'BEARDED REEDLING',
                 'ORANGE BREASTED TROGON', 'BELTED KINGFISHER', 'KILLDEAR', 'PLUSH CRESTED JAY', 'HELMET VANGA',
                 'BAR-TAILED GODWIT', 'CRESTED OROPENDOLA', 'STRIPPED MANAKIN', 'CAPE LONGCLAW', 'CREAM COLORED WOODPECKER',
                 'NORTHERN BEARDLESS TYRANNULET', 'YELLOW BELLIED FLOWERPECKER', 'RED SHOULDERED HAWK', 'RED TAILED THRUSH',
                 'STEAMER DUCK', 'RED BELLIED PITTA', 'GRAY CATBIRD', 'GUINEA TURACO', 'RUDDY SHELDUCK',
                 'RED WISKERED BULBUL', 'PATAGONIAN SIERRA FINCH', 'PHILIPPINE EAGLE', 'RED FODY', 'ANHINGA', 'VEERY',
                 'SPOTTED WHISTLING DUCK', 'BRANDT CORMARANT', 'SPOON BILED SANDPIPER', 'VULTURINE GUINEAFOWL',
                 'ENGGANO MYNA', 'YELLOW BREASTED CHAT', 'GREAT XENOPS', 'SAYS PHOEBE', 'BIRD OF PARADISE', 'LILAC ROLLER',
                 'BAIKAL TEAL', 'CINNAMON ATTILA', 'BANANAQUIT', 'JOCOTOCO ANTPITTA', 'CHUKAR PARTRIDGE', 'CRIMSON CHAT',
                 'EASTERN GOLDEN WEAVER', 'CACTUS WREN', 'BALD EAGLE', 'CAPE GLOSSY STARLING', 'BURCHELLS COURSER',
                 'IVORY BILLED ARACARI', 'NICOBAR PIGEON', 'KIWI', 'AFRICAN FIREFINCH', 'CRESTED NUTHATCH',
                 'GOLD WING WARBLER', 'WHITE BROWED CRAKE', 'DUNLIN', 'COCKATOO', 'BLUE THROATED TOUCANET',
                 'CAATINGA CACHOLOTE', 'EMU', 'FAIRY TERN', 'HARPY EAGLE', 'ANDEAN SISKIN', 'DOUBLE EYED FIG PARROT',
                 'BLUE MALKOHA', 'GREAT ARGUS', 'CUBAN TROGON', 'VIOLET TURACO', 'BLONDE CRESTED WOODPECKER',
                 'ASHY THRUSHBIRD', 'BLUE HERON', 'EURASIAN MAGPIE', 'RED WINGED BLACKBIRD', 'ZEBRA DOVE',
                 'BORNEAN BRISTLEHEAD', 'FAN TAILED WIDOW', 'WRENTIT', 'COLLARED CRESCENTCHEST', 'CANVASBACK',
                 'FOREST WAGTAIL', 'CHESTNET BELLIED EUPHONIA', 'IBERIAN MAGPIE', 'SCARLET CROWNED FRUIT DOVE',
                 'ORANGE BRESTED BUNTING', 'SCARLET TANAGER', 'ASIAN DOLLARD BIRD', 'ANDEAN LAPWING', 'MAGPIE GOOSE',
                 'KING EIDER', 'BLACK THROATED HUET', 'WHITE THROATED BEE EATER', 'TROPICAL KINGBIRD', 'PARAKETT  AUKLET',
                 'BLACK FRANCOLIN', 'ASHY STORM PETREL', 'COLLARED ARACARI', 'CRESTED AUKLET', 'GLOSSY IBIS',
                 'NORTHERN CARDINAL', 'KAGU', 'SURF SCOTER', 'PURPLE FINCH', 'ANDEAN GOOSE', 'HORNED SUNGEM', 'MYNA',
                 'COMMON HOUSE MARTIN', 'EURASIAN GOLDEN ORIOLE', 'NORTHERN SHOVELER', 'AVADAVAT', 'ANTBIRD', 'PHAINOPEPLA',
                 'POMARINE JAEGER', 'BLUE GRAY GNATCATCHER', 'CLARKS GREBE', 'APOSTLEBIRD', 'COPPERY TAILED COUCAL',
                 'ALEXANDRINE PARAKEET', 'MCKAYS BUNTING', 'CEDAR WAXWING', 'KING VULTURE', 'SAND MARTIN',
                 'SMITHS LONGSPUR', 'ALPINE CHOUGH', 'PYGMY KINGFISHER', 'GOULDIAN FINCH', 'CRESTED WOOD PARTRIDGE', 'CROW',
                 'RED KNOT', 'BROWN CREPPER', 'TAWNY FROGMOUTH', 'NOISY FRIARBIRD', 'CERULEAN WARBLER', 'CAMPO FLICKER',
                 'WHITE CHEEKED TURACO', 'BARN OWL', 'STRIPED OWL', 'TAILORBIRD', 'VIOLET BACKED STARLING', 'IVORY GULL',
                 'OSTRICH', 'ROUGH LEG BUZZARD', 'RAINBOW LORIKEET', 'BAND TAILED GUAN', 'APAPANE', 'HIMALAYAN BLUETAIL',
                 'PARUS MAJOR', 'LONG-EARED OWL', 'CRESTED FIREBACK', 'EASTERN YELLOW ROBIN', 'MARABOU STORK',
                 'EURASIAN BULLFINCH', 'BLACK TAIL CRAKE', 'GOLDEN BOWER BIRD', 'INCA TERN', 'PAINTED BUNTING',
                 'EASTERN BLUEBIRD', 'PALILA', 'HOOPOES', 'OKINAWA RAIL', 'AUSTRALASIAN FIGBIRD', 'CHIPPING SPARROW',
                 'TRICOLORED BLACKBIRD', 'AMERICAN FLAMINGO', 'WILLOW PTARMIGAN', 'ANNAS HUMMINGBIRD', 'CINNAMON TEAL',
                 'SCARLET FACED LIOCICHLA', 'WOODLAND KINGFISHER', 'VENEZUELIAN TROUPIAL', 'HEPATIC TANAGER', 'MALEO',
                 'IWI', 'WHITE NECKED RAVEN', 'PINK ROBIN', 'BOBOLINK', 'MANDRIN DUCK', 'RED BROWED FINCH', 'PYRRHULOXIA',
                 'NORTHERN PARULA', 'COPPERSMITH BARBET', 'AMERICAN AVOCET', 'EVENING GROSBEAK', 'RED HEADED DUCK',
                 'TREE SWALLOW', 'COMMON GRACKLE', 'SCARLET MACAW', 'HORNED GUAN', 'CHESTNUT WINGED CUCKOO',
                 'BLACK VENTED SHEARWATER', 'RED CROSSBILL', 'CAPUCHINBIRD', 'MANGROVE CUCKOO', 'CRAB PLOVER',
                 'CINNAMON FLYCATCHER', 'WILD TURKEY', 'DUSKY ROBIN', 'VIOLET GREEN SWALLOW', 'AUSTRAL CANASTERO',
                 'BUSH TURKEY', 'GOLDEN PARAKEET', 'LESSER ADJUTANT', 'GREEN JAY', 'ALTAMIRA YELLOWTHROAT',
                 'FRILL BACK PIGEON', 'BEARDED BELLBIRD', 'FLAME BOWERBIRD', 'PUNA TEAL', 'LIMPKIN', 'RUFUOS MOTMOT',
                 'CRESTED KINGFISHER', 'NORTHERN JACANA', 'ECUADORIAN HILLSTAR', 'ROADRUNNER', 'BLUE GROUSE',
                 'CAPPED HERON', 'TEAL DUCK', 'DARK EYED JUNCO', 'LOGGERHEAD SHRIKE', 'CLARKS NUTCRACKER', 'GILDED FLICKER',
                 'CHUCAO TAPACULO', 'BALI STARLING', 'SNOW PARTRIDGE', 'GREY CUCKOOSHRIKE', 'VERDIN', 'GREAT GRAY OWL',
                 'ROCK DOVE', 'BREWERS BLACKBIRD', 'LUCIFER HUMMINGBIRD', 'BLOOD PHEASANT', 'ORNATE HAWK EAGLE',
                 'AFRICAN PIED HORNBILL', 'CHARA DE COLLAR', 'TOWNSENDS WARBLER', 'D-ARNAUDS BARBET', 'MERLIN',
                 'OYSTER CATCHER', 'VARIED THRUSH', 'RUFOUS TREPE', 'SRI LANKA BLUE MAGPIE', 'SNOWY SHEATHBILL',
                 'LARK BUNTING', 'DOUBLE BARRED FINCH', 'FAIRY BLUEBIRD', 'CRIMSON SUNBIRD', 'HARLEQUIN QUAIL',
                 'HOUSE SPARROW', 'AMERICAN DIPPER', 'CRESTED CARACARA', 'NORTHERN GANNET', 'SCARLET IBIS',
                 'MALACHITE KINGFISHER', 'INDIAN PITTA', 'EASTERN MEADOWLARK', 'REGENT BOWERBIRD',
                 'WILSONS BIRD OF PARADISE', 'COMMON IORA', 'BLACK NECKED STILT', 'SHORT BILLED DOWITCHER',
                 'BLACK-THROATED SPARROW', 'DARJEELING WOODPECKER', 'NORTHERN FLICKER', 'BANDED STILT',
                 'GREY HEADED CHACHALACA', 'PURPLE GALLINULE', 'CANARY', 'TAKAHE', 'JANDAYA PARAKEET', 'FLAME TANAGER',
                 'CURL CRESTED ARACURI', 'FASCIATED WREN', 'GREATER PEWEE', 'RED FACED CORMORANT', 'GREAT JACAMAR',
                 'ROSE BREASTED GROSBEAK', 'ROYAL FLYCATCHER', 'NORTHERN FULMAR', 'EARED PITA', 'BULWERS PHEASANT',
                 'HORNED LARK', 'HAWFINCH', 'COCK OF THE  ROCK', 'TIT MOUSE', 'GRAY PARTRIDGE', 'AZURE BREASTED PITTA',
                 'ANIANIAU', 'WOOD DUCK', 'KNOB BILLED DUCK', 'GROVED BILLED ANI', 'RED FACED WARBLER', 'HIMALAYAN MONAL',
                 'DEMOISELLE CRANE', 'CRESTED COUA', 'QUETZAL', 'NORTHERN GOSHAWK', 'GOLDEN CHLOROPHONIA',
                 'RUBY CROWNED KINGLET', 'PURPLE SWAMPHEN', 'COMMON FIRECREST', 'TURQUOISE MOTMOT', 'CASSOWARY',
                 'INDIAN BUSTARD', 'KOOKABURRA', 'SANDHILL CRANE', 'RING-NECKED PHEASANT', 'MASKED BOBWHITE',
                 'EASTERN ROSELLA', 'GREY HEADED FISH EAGLE', 'PURPLE MARTIN', 'VICTORIA CROWNED PIGEON', 'SHOEBILL',
                 'SNOWY OWL', 'AFRICAN CROWNED CRANE', 'GREAT POTOO', 'STORK BILLED KINGFISHER', 'BLACK HEADED CAIQUE',
                 'GOLDEN PHEASANT', 'AFRICAN OYSTER CATCHER', 'ASIAN CRESTED IBIS', 'EASTERN WIP POOR WILL', 'LITTLE AUK',
                 'BLACK-NECKED GREBE', 'ABBOTTS BOOBY', 'BALTIMORE ORIOLE', 'VIOLET CUCKOO', 'COMMON STARLING', 'HAMERKOP',
                 'INDIAN VULTURE', 'JAPANESE ROBIN', 'BLACKBURNIAM WARBLER', 'WHIMBREL', 'YELLOW HEADED BLACKBIRD',
                 'SPOTTED CATBIRD', 'BLACK COCKATO', 'SPANGLED COTINGA', 'FAIRY PENGUIN', 'MALAGASY WHITE EYE',
                 'HAWAIIAN GOOSE', 'PEACOCK', 'BEARDED BARBET', 'TURKEY VULTURE', 'JACK SNIPE', 'ASIAN GREEN BEE EATER',
                 'BLACK VULTURE', 'BROWN THRASHER', 'BLUE DACNIS', 'DAURIAN REDSTART', 'STRIATED CARACARA',
                 'GREATER PRAIRIE CHICKEN', 'GOLDEN CHEEKED WARBLER', 'DOUBLE BRESTED CORMARANT', 'JAVA SPARROW',
                 'BAY-BREASTED WARBLER', 'AZURE TIT', 'HOATZIN', 'GO AWAY BIRD', 'ELLIOTS  PHEASANT', 'JACOBIN PIGEON',
                 'CRESTED SERPENT EAGLE', 'IMPERIAL SHAQ', 'BARROWS GOLDENEYE', 'FRIGATE', 'TRUMPTER SWAN',
                 'INLAND DOTTEREL', 'SAMATRAN THRUSH', 'BLACK AND YELLOW BROADBILL', 'BORNEAN LEAFBIRD', 'LAZULI BUNTING',
                 'EUROPEAN GOLDFINCH', 'AMERICAN REDSTART', 'CRANE HAWK', 'NORTHERN RED BISHOP', 'GOLDEN EAGLE']
        class_names.sort()

        class_labels = class_names
        score = tf.nn.softmax(predictions[0])
        print(f"{class_labels[tf.argmax(score)]}")

        # Lấy index của lớp có xác suất cao nhất
        # predicted_index = np.argmax(prediction)

        # Hiển thị kết quả dự đoán
        # predicted_class = class_names[predicted_index]
        result_label.config(text=f"Predicted Class: {class_labels[tf.argmax(score)]}")


def load_and_preprocess_image(image_path):
    # Đọc hình ảnh sử dụng PIL
    image = Image.open(image_path)

    # Preprocess the image
    img = image.resize((224, 224))
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)

    return img_array


def on_select():
    global selected_image_path
    file_path = filedialog.askopenfilename()
    if file_path:
        selected_image_path = file_path
        img = Image.open(file_path)
        img.thumbnail((650, 650))
        img = ImageTk.PhotoImage(img)
        panel.configure(image=img)
        panel.image = img


root = tk.Tk()
root.title("Bird Classification App")

panel = tk.Label(root)
panel.pack()

classify_button = tk.Button(root, text="Classify", command=classify_image)
classify_button.pack()

select_button = tk.Button(root, text="Select Image", command=on_select)
select_button.pack()

result_label = tk.Label(root, text="", font=("Arial", 24))
result_label.pack()

root.mainloop()
